services:
  api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: rifflog
      POSTGRES_PASSWORD: devriffs
      POSTGRES_DB: rifflog
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
